/*
 * Owner: production native bridge skeleton 写集。
 * Truth: 承载 internal native bridge C ABI、AppKit / QuartzCore class facts、
 * main-thread admission、token-backed NSView first slice、CAMetalLayer allocation
 * / table / create-destroy / NSView attachment first slice、Metal device binding
 * first slice、MTLRenderPassDescriptor create/destroy first slice、
 * MTLRenderPipelineDescriptor no-draw create/config/destroy first slice、
 * shader library / function no-draw create/lookup/destroy first slice、
 * MTLRenderPipelineState no-draw create/destroy first slice、
 * MTLBuffer no-submit create/destroy/data-upload first slice、
 * draw call no-submit still-blocked facts、token-backed NSWindow harness
 * create/destroy first slice、NSWindow content-view attachment first slice、
 * visible-order native guard no-side-effect facts、NSApplication native guard
 * no-side-effect facts、shared-application accessor call containment facts
 * 与内部 status taxonomy，
 * 不是 public runtime API。
 * Stop-line: 只允许 token-backed NSWindow harness 创建 / 销毁不可见窗口对象，
 * 以及不可见 NSWindow.contentView token wiring、visible-order guard facts、
 * NSApplication guard facts 与 accessor call containment facts；
 * 不创建应用、drawable、绘制资源，
 * command buffer / render pass descriptor / pipeline descriptor / shader
 * library / pipeline state / vertex buffer first slice 不创建 encoder，
 * 不绑定 pipeline 或 vertex buffer，不 draw，
 * 不 commit / present / render，
 * 不返回指针身份。
 * Same-shape Boundary Brake: callable surface 只是无副作用 native surface，不是 bridge-ready、backend-ready、render-ready 或 public API permission。
 */
#ifndef CJGUI_NATIVE_BRIDGE_H
#define CJGUI_NATIVE_BRIDGE_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * 该 enum 固定 production bridge 的内部状态分类词汇。
 * 当前文件未接入仓颉 FFI，未承诺 runtime resource behavior。
 */
typedef enum CjguiNativeBridgeSkeletonStatus {
    CJGUI_NATIVE_BRIDGE_SKELETON_STATUS_OK = 0,
    CJGUI_NATIVE_BRIDGE_SKELETON_STATUS_NOT_WIRED = 1,
    CJGUI_NATIVE_BRIDGE_SKELETON_STATUS_MAIN_THREAD_REQUIRED = 2,
    CJGUI_NATIVE_BRIDGE_SKELETON_STATUS_TOKEN_UNAVAILABLE = 3,
    CJGUI_NATIVE_BRIDGE_SKELETON_STATUS_RESOURCE_DENIED = 4,
    CJGUI_NATIVE_BRIDGE_SKELETON_STATUS_TEARDOWN_DENIED = 5
} CjguiNativeBridgeSkeletonStatus;

typedef enum CjguiNativeBridgeSkeletonCategory {
    CJGUI_NATIVE_BRIDGE_SKELETON_CATEGORY_NONE = 0,
    CJGUI_NATIVE_BRIDGE_SKELETON_CATEGORY_ADMISSION = 1,
    CJGUI_NATIVE_BRIDGE_SKELETON_CATEGORY_CONFINEMENT = 2,
    CJGUI_NATIVE_BRIDGE_SKELETON_CATEGORY_TOKEN = 3,
    CJGUI_NATIVE_BRIDGE_SKELETON_CATEGORY_TEARDOWN = 4,
    CJGUI_NATIVE_BRIDGE_SKELETON_CATEGORY_RESOURCE = 5
} CjguiNativeBridgeSkeletonCategory;

typedef enum CjguiNativeBridgeSurfaceCapability {
    CJGUI_NATIVE_BRIDGE_SURFACE_CAPABILITY_VERSION_QUERY = 1u << 0,
    CJGUI_NATIVE_BRIDGE_SURFACE_CAPABILITY_STATUS_QUERY = 1u << 1,
    CJGUI_NATIVE_BRIDGE_SURFACE_CAPABILITY_CAPABILITY_QUERY = 1u << 2,
    CJGUI_NATIVE_BRIDGE_SURFACE_CAPABILITY_NO_RESOURCE_ADMISSION = 1u << 3,
    CJGUI_NATIVE_BRIDGE_SURFACE_CAPABILITY_MAIN_THREAD_QUERY = 1u << 4,
    CJGUI_NATIVE_BRIDGE_SURFACE_CAPABILITY_TOKEN_TABLE_SHELL = 1u << 5,
    CJGUI_NATIVE_BRIDGE_SURFACE_CAPABILITY_TOKEN_ISSUE_REVOKE = 1u << 6,
    CJGUI_NATIVE_BRIDGE_SURFACE_CAPABILITY_TEARDOWN_ADMISSION = 1u << 7,
    CJGUI_NATIVE_BRIDGE_SURFACE_CAPABILITY_APPKIT_IMPORT_BOUNDARY = 1u << 8,
    CJGUI_NATIVE_BRIDGE_SURFACE_CAPABILITY_APPKIT_CLASS_AVAILABILITY = 1u << 9,
    CJGUI_NATIVE_BRIDGE_SURFACE_CAPABILITY_APPKIT_MAIN_THREAD_ADMISSION = 1u << 10,
    CJGUI_NATIVE_BRIDGE_SURFACE_CAPABILITY_PLATFORM_OBJECT_NO_OBJECT_CREATION = 1u << 11,
    CJGUI_NATIVE_BRIDGE_SURFACE_CAPABILITY_NSVIEW_OBJECT_TABLE_SHELL = 1u << 12,
    CJGUI_NATIVE_BRIDGE_SURFACE_CAPABILITY_NSVIEW_CREATE_DESTROY = 1u << 13,
    CJGUI_NATIVE_BRIDGE_SURFACE_CAPABILITY_CAMETALLAYER_NO_ATTACH = 1u << 14,
    CJGUI_NATIVE_BRIDGE_SURFACE_CAPABILITY_CAMETALLAYER_ALLOCATION = 1u << 15,
    CJGUI_NATIVE_BRIDGE_SURFACE_CAPABILITY_CAMETALLAYER_OBJECT_TABLE = 1u << 16,
    CJGUI_NATIVE_BRIDGE_SURFACE_CAPABILITY_CAMETALLAYER_CREATE_DESTROY =
        1u << 17,
    CJGUI_NATIVE_BRIDGE_SURFACE_CAPABILITY_CAMETALLAYER_NSVIEW_ATTACHMENT =
        1u << 18,
    CJGUI_NATIVE_BRIDGE_SURFACE_CAPABILITY_METAL_DEVICE_AVAILABILITY =
        1u << 19,
    CJGUI_NATIVE_BRIDGE_SURFACE_CAPABILITY_METAL_DEVICE_CREATE_DESTROY =
        1u << 20,
    CJGUI_NATIVE_BRIDGE_SURFACE_CAPABILITY_METAL_DEVICE_LAYER_BINDING =
        1u << 21,
    CJGUI_NATIVE_BRIDGE_SURFACE_CAPABILITY_COMMAND_QUEUE_CREATE_DESTROY =
        1u << 22,
    CJGUI_NATIVE_BRIDGE_SURFACE_CAPABILITY_COMMAND_BUFFER_CREATE_DESTROY =
        1u << 23,
    CJGUI_NATIVE_BRIDGE_SURFACE_CAPABILITY_RENDER_PASS_DESCRIPTOR_CREATE_DESTROY =
        1u << 24,
    CJGUI_NATIVE_BRIDGE_SURFACE_CAPABILITY_PIPELINE_DESCRIPTOR_CREATE_DESTROY =
        1u << 25,
    CJGUI_NATIVE_BRIDGE_SURFACE_CAPABILITY_SHADER_LIBRARY_CREATE_DESTROY =
        1u << 26,
    CJGUI_NATIVE_BRIDGE_SURFACE_CAPABILITY_SHADER_FUNCTION_LOOKUP =
        1u << 27,
    CJGUI_NATIVE_BRIDGE_SURFACE_CAPABILITY_PIPELINE_STATE_CREATE_DESTROY =
        1u << 28,
    CJGUI_NATIVE_BRIDGE_SURFACE_CAPABILITY_VERTEX_BUFFER_CREATE_DESTROY =
        1u << 29,
    CJGUI_NATIVE_BRIDGE_SURFACE_CAPABILITY_VERTEX_BUFFER_DATA_UPLOAD =
        1u << 30,
    CJGUI_NATIVE_BRIDGE_SURFACE_CAPABILITY_NSWINDOW_HARNESS_CREATE_DESTROY =
        1u << 31
} CjguiNativeBridgeSurfaceCapability;

enum {
    CJGUI_NATIVE_BRIDGE_SURFACE_VERSION = 1u,
    CJGUI_NATIVE_BRIDGE_TOKEN_INVALID = 0u,
    CJGUI_NATIVE_BRIDGE_TOKEN_TABLE_CAPACITY = 8u,
    CJGUI_NATIVE_BRIDGE_NSVIEW_TABLE_CAPACITY = 4u,
    CJGUI_NATIVE_BRIDGE_CAMETALLAYER_TABLE_CAPACITY = 4u,
    CJGUI_NATIVE_BRIDGE_METAL_DEVICE_TABLE_CAPACITY = 2u,
    CJGUI_NATIVE_BRIDGE_COMMAND_QUEUE_TABLE_CAPACITY = 2u,
    CJGUI_NATIVE_BRIDGE_COMMAND_BUFFER_TABLE_CAPACITY = 2u,
    CJGUI_NATIVE_BRIDGE_RENDER_PASS_DESCRIPTOR_TABLE_CAPACITY = 2u,
    CJGUI_NATIVE_BRIDGE_PIPELINE_DESCRIPTOR_TABLE_CAPACITY = 2u,
    CJGUI_NATIVE_BRIDGE_SHADER_LIBRARY_TABLE_CAPACITY = 2u,
    CJGUI_NATIVE_BRIDGE_SHADER_FUNCTION_TABLE_CAPACITY = 4u,
    CJGUI_NATIVE_BRIDGE_PIPELINE_STATE_TABLE_CAPACITY = 2u,
    CJGUI_NATIVE_BRIDGE_VERTEX_BUFFER_TABLE_CAPACITY = 2u,
    CJGUI_NATIVE_BRIDGE_NSWINDOW_HARNESS_TABLE_CAPACITY = 2u,
    CJGUI_NATIVE_BRIDGE_TOKEN_SLOT_BITS = 16u,
    CJGUI_NATIVE_BRIDGE_TOKEN_SLOT_MASK = 0xffffu
};

typedef enum CjguiNativeBridgeTokenClassification {
    CJGUI_NATIVE_BRIDGE_TOKEN_CLASS_INVALID = 0,
    CJGUI_NATIVE_BRIDGE_TOKEN_CLASS_VALID = 1,
    CJGUI_NATIVE_BRIDGE_TOKEN_CLASS_STALE = -2,
    CJGUI_NATIVE_BRIDGE_TOKEN_CLASS_MAIN_THREAD_REQUIRED = -3,
    CJGUI_NATIVE_BRIDGE_TOKEN_CLASS_CAPACITY_EXHAUSTED = -4
} CjguiNativeBridgeTokenClassification;

typedef enum CjguiNativeBridgeTeardownClassification {
    CJGUI_NATIVE_BRIDGE_TEARDOWN_CLASS_DESTROY_NOT_SUPPORTED = -10,
    CJGUI_NATIVE_BRIDGE_TEARDOWN_CLASS_REVOKE_BEFORE_DESTROY_REQUIRED = -11,
    CJGUI_NATIVE_BRIDGE_TEARDOWN_CLASS_DOUBLE_DESTROY_DENIED = -12,
    CJGUI_NATIVE_BRIDGE_TEARDOWN_CLASS_DANGLING_TOKEN_DENIED = -13
} CjguiNativeBridgeTeardownClassification;

typedef enum CjguiNativeBridgeAppKitImportClassification {
    CJGUI_NATIVE_BRIDGE_APPKIT_IMPORT_AVAILABLE = 20,
    CJGUI_NATIVE_BRIDGE_APPKIT_NO_OBJECT_ADMISSION = 21,
    CJGUI_NATIVE_BRIDGE_APPKIT_NSWINDOW_CLASS_AVAILABLE = 22,
    CJGUI_NATIVE_BRIDGE_APPKIT_NSVIEW_CLASS_AVAILABLE = 23,
    CJGUI_NATIVE_BRIDGE_APPKIT_CLASS_LOOKUP_NO_OBJECT_ADMISSION = 24,
    CJGUI_NATIVE_BRIDGE_APPKIT_PLATFORM_OBJECT_MAIN_THREAD_REQUIRED = 25,
    CJGUI_NATIVE_BRIDGE_APPKIT_PLATFORM_OBJECT_MAIN_THREAD_ADMITTED = 26,
    CJGUI_NATIVE_BRIDGE_PLATFORM_OBJECT_CREATE_NO_OBJECT_ADMISSION = 27,
    CJGUI_NATIVE_BRIDGE_PLATFORM_OBJECT_CREATE_REQUIRES_MAIN_THREAD = 28,
    CJGUI_NATIVE_BRIDGE_PLATFORM_OBJECT_CREATE_REQUIRES_TOKEN_CONTRACT = 29,
    CJGUI_NATIVE_BRIDGE_PLATFORM_OBJECT_CREATE_STILL_BLOCKED = -20,
    CJGUI_NATIVE_BRIDGE_PLATFORM_OBJECT_ALLOCATION_STILL_BLOCKED = -21,
    CJGUI_NATIVE_BRIDGE_APPKIT_PLATFORM_OBJECT_BACKGROUND_THREAD_DENIED = -22,
    CJGUI_NATIVE_BRIDGE_APPKIT_PLATFORM_OBJECT_CREATION_STILL_BLOCKED = -23,
    CJGUI_NATIVE_BRIDGE_PLATFORM_OBJECT_CREATE_ALLOCATION_BLOCKED = -24
} CjguiNativeBridgeAppKitImportClassification;

typedef enum CjguiNativeBridgeNsViewTableClassification {
    CJGUI_NATIVE_BRIDGE_NSVIEW_TABLE_EMPTY = 30,
    CJGUI_NATIVE_BRIDGE_NSVIEW_TABLE_TOKEN_NOT_BOUND = -30,
    CJGUI_NATIVE_BRIDGE_NSVIEW_TABLE_ALLOCATION_BLOCKED = -31,
    CJGUI_NATIVE_BRIDGE_NSVIEW_TABLE_DESTROY_BLOCKED = -32
} CjguiNativeBridgeNsViewTableClassification;

typedef enum CjguiNativeBridgeNsViewLifecycleClassification {
    CJGUI_NATIVE_BRIDGE_NSVIEW_TOKEN_BOUND = 40,
    CJGUI_NATIVE_BRIDGE_NSVIEW_CREATE_MAIN_THREAD_REQUIRED = -40,
    CJGUI_NATIVE_BRIDGE_NSVIEW_DESTROY_MAIN_THREAD_REQUIRED = -41,
    CJGUI_NATIVE_BRIDGE_NSVIEW_INVALID_TOKEN_DENIED = -42,
    CJGUI_NATIVE_BRIDGE_NSVIEW_STALE_TOKEN_DENIED = -43,
    CJGUI_NATIVE_BRIDGE_NSVIEW_TOKEN_NOT_BOUND = -44,
    CJGUI_NATIVE_BRIDGE_NSVIEW_CAPACITY_EXHAUSTED = -45,
    CJGUI_NATIVE_BRIDGE_NSVIEW_DOUBLE_DESTROY_DENIED = -46,
    CJGUI_NATIVE_BRIDGE_NSVIEW_ALLOCATION_FAILED = -47,
    CJGUI_NATIVE_BRIDGE_NSVIEW_OUT_TOKEN_REQUIRED = -48
} CjguiNativeBridgeNsViewLifecycleClassification;

typedef enum CjguiNativeBridgeCAMetalLayerNoAttachClassification {
    CJGUI_NATIVE_BRIDGE_QUARTZCORE_IMPORT_AVAILABLE = 50,
    CJGUI_NATIVE_BRIDGE_CAMETALLAYER_CLASS_AVAILABLE = 51,
    CJGUI_NATIVE_BRIDGE_CAMETALLAYER_NO_ATTACH_ADMISSION = 52,
    CJGUI_NATIVE_BRIDGE_CAMETALLAYER_ALLOCATION_STILL_BLOCKED = -50,
    CJGUI_NATIVE_BRIDGE_CAMETALLAYER_DEVICE_BINDING_STILL_BLOCKED = -51
} CjguiNativeBridgeCAMetalLayerNoAttachClassification;

typedef enum CjguiNativeBridgeCAMetalLayerAllocationClassification {
    CJGUI_NATIVE_BRIDGE_CAMETALLAYER_ALLOCATION_FEASIBLE = 60,
    CJGUI_NATIVE_BRIDGE_CAMETALLAYER_ALLOCATION_NO_ATTACH_ADMISSION = 61,
    CJGUI_NATIVE_BRIDGE_CAMETALLAYER_ALLOCATION_FEASIBILITY_OBSERVED = 62,
    CJGUI_NATIVE_BRIDGE_CAMETALLAYER_ALLOCATION_MAIN_THREAD_REQUIRED = -60,
    CJGUI_NATIVE_BRIDGE_CAMETALLAYER_ALLOCATION_FAILED = -61,
    CJGUI_NATIVE_BRIDGE_CAMETALLAYER_ALLOCATION_DEVICE_BINDING_BLOCKED = -62
} CjguiNativeBridgeCAMetalLayerAllocationClassification;

typedef enum CjguiNativeBridgeCAMetalLayerTableClassification {
    CJGUI_NATIVE_BRIDGE_CAMETALLAYER_TABLE_EMPTY = 70,
    CJGUI_NATIVE_BRIDGE_CAMETALLAYER_TABLE_TOKEN_NOT_BOUND = -70,
    CJGUI_NATIVE_BRIDGE_CAMETALLAYER_TABLE_ALLOCATION_BLOCKED = -71,
    CJGUI_NATIVE_BRIDGE_CAMETALLAYER_TABLE_DESTROY_BLOCKED = -72
} CjguiNativeBridgeCAMetalLayerTableClassification;

typedef enum CjguiNativeBridgeCAMetalLayerLifecycleClassification {
    CJGUI_NATIVE_BRIDGE_CAMETALLAYER_TOKEN_BOUND = 80,
    CJGUI_NATIVE_BRIDGE_CAMETALLAYER_CREATE_MAIN_THREAD_REQUIRED = -80,
    CJGUI_NATIVE_BRIDGE_CAMETALLAYER_DESTROY_MAIN_THREAD_REQUIRED = -81,
    CJGUI_NATIVE_BRIDGE_CAMETALLAYER_INVALID_TOKEN_DENIED = -82,
    CJGUI_NATIVE_BRIDGE_CAMETALLAYER_STALE_TOKEN_DENIED = -83,
    CJGUI_NATIVE_BRIDGE_CAMETALLAYER_TOKEN_NOT_BOUND = -84,
    CJGUI_NATIVE_BRIDGE_CAMETALLAYER_CAPACITY_EXHAUSTED = -85,
    CJGUI_NATIVE_BRIDGE_CAMETALLAYER_DOUBLE_DESTROY_DENIED = -86,
    CJGUI_NATIVE_BRIDGE_CAMETALLAYER_ALLOCATION_LIFECYCLE_FAILED = -87,
    CJGUI_NATIVE_BRIDGE_CAMETALLAYER_OUT_TOKEN_REQUIRED = -88
} CjguiNativeBridgeCAMetalLayerLifecycleClassification;

typedef enum CjguiNativeBridgeCAMetalLayerAttachmentClassification {
    CJGUI_NATIVE_BRIDGE_CAMETALLAYER_ATTACHMENT_ATTACHED = 90,
    CJGUI_NATIVE_BRIDGE_CAMETALLAYER_ATTACHMENT_NOT_ATTACHED = -90,
    CJGUI_NATIVE_BRIDGE_CAMETALLAYER_ATTACHMENT_MAIN_THREAD_REQUIRED = -91,
    CJGUI_NATIVE_BRIDGE_CAMETALLAYER_ATTACHMENT_INVALID_LAYER_TOKEN = -92,
    CJGUI_NATIVE_BRIDGE_CAMETALLAYER_ATTACHMENT_INVALID_VIEW_TOKEN = -93,
    CJGUI_NATIVE_BRIDGE_CAMETALLAYER_ATTACHMENT_STALE_LAYER_TOKEN = -94,
    CJGUI_NATIVE_BRIDGE_CAMETALLAYER_ATTACHMENT_STALE_VIEW_TOKEN = -95,
    CJGUI_NATIVE_BRIDGE_CAMETALLAYER_ATTACHMENT_DOUBLE_DETACH_DENIED = -96,
    CJGUI_NATIVE_BRIDGE_CAMETALLAYER_ATTACHMENT_DOUBLE_ATTACH_DENIED = -97,
    CJGUI_NATIVE_BRIDGE_CAMETALLAYER_ATTACHMENT_LAYER_TOKEN_NOT_BOUND = -98,
    CJGUI_NATIVE_BRIDGE_CAMETALLAYER_ATTACHMENT_VIEW_TOKEN_NOT_BOUND = -99,
    CJGUI_NATIVE_BRIDGE_CAMETALLAYER_ATTACHMENT_DEVICE_BINDING_BLOCKED = -100,
    CJGUI_NATIVE_BRIDGE_CAMETALLAYER_ATTACHMENT_DETACH_BEFORE_DESTROY_REQUIRED =
        -101
} CjguiNativeBridgeCAMetalLayerAttachmentClassification;

typedef enum CjguiNativeBridgeMetalDeviceAvailabilityClassification {
    CJGUI_NATIVE_BRIDGE_METAL_IMPORT_AVAILABLE = 100,
    CJGUI_NATIVE_BRIDGE_METAL_DEFAULT_DEVICE_AVAILABLE = 101,
    CJGUI_NATIVE_BRIDGE_METAL_DEVICE_NO_COMMAND_QUEUE_ADMISSION = -110,
    CJGUI_NATIVE_BRIDGE_METAL_DEFAULT_DEVICE_UNAVAILABLE = -111,
    CJGUI_NATIVE_BRIDGE_METAL_DEVICE_CREATION_STILL_BLOCKED = -112
} CjguiNativeBridgeMetalDeviceAvailabilityClassification;

typedef enum CjguiNativeBridgeMetalDeviceLifecycleClassification {
    CJGUI_NATIVE_BRIDGE_METAL_DEVICE_TOKEN_BOUND = 120,
    CJGUI_NATIVE_BRIDGE_METAL_DEVICE_CREATE_MAIN_THREAD_REQUIRED = -120,
    CJGUI_NATIVE_BRIDGE_METAL_DEVICE_DESTROY_MAIN_THREAD_REQUIRED = -121,
    CJGUI_NATIVE_BRIDGE_METAL_DEVICE_INVALID_TOKEN_DENIED = -122,
    CJGUI_NATIVE_BRIDGE_METAL_DEVICE_STALE_TOKEN_DENIED = -123,
    CJGUI_NATIVE_BRIDGE_METAL_DEVICE_TOKEN_NOT_BOUND = -124,
    CJGUI_NATIVE_BRIDGE_METAL_DEVICE_CAPACITY_EXHAUSTED = -125,
    CJGUI_NATIVE_BRIDGE_METAL_DEVICE_DOUBLE_DESTROY_DENIED = -126,
    CJGUI_NATIVE_BRIDGE_METAL_DEVICE_CREATION_FAILED = -127,
    CJGUI_NATIVE_BRIDGE_METAL_DEVICE_OUT_TOKEN_REQUIRED = -128,
    CJGUI_NATIVE_BRIDGE_METAL_DEVICE_COMMAND_QUEUE_STILL_BLOCKED = -129,
    CJGUI_NATIVE_BRIDGE_METAL_DEVICE_COMMAND_QUEUE_DESTROY_BEFORE_DEVICE_REQUIRED =
        -130,
    CJGUI_NATIVE_BRIDGE_METAL_DEVICE_PIPELINE_STATE_DESTROY_BEFORE_DEVICE_REQUIRED =
        -131,
    CJGUI_NATIVE_BRIDGE_METAL_DEVICE_VERTEX_BUFFER_DESTROY_BEFORE_DEVICE_REQUIRED =
        -132
} CjguiNativeBridgeMetalDeviceLifecycleClassification;

typedef enum CjguiNativeBridgeMetalDeviceLayerBindingClassification {
    CJGUI_NATIVE_BRIDGE_METAL_DEVICE_LAYER_BOUND = 140,
    CJGUI_NATIVE_BRIDGE_METAL_DEVICE_LAYER_NOT_BOUND = -140,
    CJGUI_NATIVE_BRIDGE_METAL_DEVICE_LAYER_BIND_MAIN_THREAD_REQUIRED = -141,
    CJGUI_NATIVE_BRIDGE_METAL_DEVICE_LAYER_INVALID_LAYER_TOKEN = -142,
    CJGUI_NATIVE_BRIDGE_METAL_DEVICE_LAYER_INVALID_DEVICE_TOKEN = -143,
    CJGUI_NATIVE_BRIDGE_METAL_DEVICE_LAYER_STALE_LAYER_TOKEN = -144,
    CJGUI_NATIVE_BRIDGE_METAL_DEVICE_LAYER_STALE_DEVICE_TOKEN = -145,
    CJGUI_NATIVE_BRIDGE_METAL_DEVICE_LAYER_DOUBLE_UNBIND_DENIED = -146,
    CJGUI_NATIVE_BRIDGE_METAL_DEVICE_LAYER_DOUBLE_BIND_DENIED = -147,
    CJGUI_NATIVE_BRIDGE_METAL_DEVICE_LAYER_TOKEN_NOT_BOUND = -148,
    CJGUI_NATIVE_BRIDGE_METAL_DEVICE_LAYER_DEVICE_TOKEN_NOT_BOUND = -149,
    CJGUI_NATIVE_BRIDGE_METAL_DEVICE_LAYER_DRAWABLE_STILL_BLOCKED = -150,
    CJGUI_NATIVE_BRIDGE_METAL_DEVICE_LAYER_DETACH_BEFORE_DESTROY_REQUIRED =
        -151
} CjguiNativeBridgeMetalDeviceLayerBindingClassification;

typedef enum CjguiNativeBridgeCommandQueueLifecycleClassification {
    CJGUI_NATIVE_BRIDGE_COMMAND_QUEUE_TOKEN_BOUND = 160,
    CJGUI_NATIVE_BRIDGE_COMMAND_QUEUE_CREATE_MAIN_THREAD_REQUIRED = -160,
    CJGUI_NATIVE_BRIDGE_COMMAND_QUEUE_DESTROY_MAIN_THREAD_REQUIRED = -161,
    CJGUI_NATIVE_BRIDGE_COMMAND_QUEUE_INVALID_TOKEN_DENIED = -162,
    CJGUI_NATIVE_BRIDGE_COMMAND_QUEUE_STALE_TOKEN_DENIED = -163,
    CJGUI_NATIVE_BRIDGE_COMMAND_QUEUE_TOKEN_NOT_BOUND = -164,
    CJGUI_NATIVE_BRIDGE_COMMAND_QUEUE_CAPACITY_EXHAUSTED = -165,
    CJGUI_NATIVE_BRIDGE_COMMAND_QUEUE_DOUBLE_DESTROY_DENIED = -166,
    CJGUI_NATIVE_BRIDGE_COMMAND_QUEUE_CREATION_FAILED = -167,
    CJGUI_NATIVE_BRIDGE_COMMAND_QUEUE_OUT_TOKEN_REQUIRED = -168,
    CJGUI_NATIVE_BRIDGE_COMMAND_QUEUE_COMMAND_BUFFER_STILL_BLOCKED = -169,
    CJGUI_NATIVE_BRIDGE_COMMAND_QUEUE_INVALID_DEVICE_TOKEN = -170,
    CJGUI_NATIVE_BRIDGE_COMMAND_QUEUE_STALE_DEVICE_TOKEN = -171,
    CJGUI_NATIVE_BRIDGE_COMMAND_QUEUE_DEVICE_TOKEN_NOT_BOUND = -172,
    CJGUI_NATIVE_BRIDGE_COMMAND_QUEUE_COMMAND_BUFFER_DESTROY_BEFORE_QUEUE_REQUIRED =
        -173
} CjguiNativeBridgeCommandQueueLifecycleClassification;

typedef enum CjguiNativeBridgeCommandBufferLifecycleClassification {
    CJGUI_NATIVE_BRIDGE_COMMAND_BUFFER_TOKEN_BOUND = 180,
    CJGUI_NATIVE_BRIDGE_COMMAND_BUFFER_CREATE_MAIN_THREAD_REQUIRED = -180,
    CJGUI_NATIVE_BRIDGE_COMMAND_BUFFER_DESTROY_MAIN_THREAD_REQUIRED = -181,
    CJGUI_NATIVE_BRIDGE_COMMAND_BUFFER_INVALID_TOKEN_DENIED = -182,
    CJGUI_NATIVE_BRIDGE_COMMAND_BUFFER_STALE_TOKEN_DENIED = -183,
    CJGUI_NATIVE_BRIDGE_COMMAND_BUFFER_TOKEN_NOT_BOUND = -184,
    CJGUI_NATIVE_BRIDGE_COMMAND_BUFFER_CAPACITY_EXHAUSTED = -185,
    CJGUI_NATIVE_BRIDGE_COMMAND_BUFFER_DOUBLE_DESTROY_DENIED = -186,
    CJGUI_NATIVE_BRIDGE_COMMAND_BUFFER_CREATION_FAILED = -187,
    CJGUI_NATIVE_BRIDGE_COMMAND_BUFFER_OUT_TOKEN_REQUIRED = -188,
    CJGUI_NATIVE_BRIDGE_COMMAND_BUFFER_COMMIT_STILL_BLOCKED = -189,
    CJGUI_NATIVE_BRIDGE_COMMAND_BUFFER_ENCODER_CREATION_STILL_BLOCKED = -190,
    CJGUI_NATIVE_BRIDGE_COMMAND_BUFFER_INVALID_QUEUE_TOKEN = -191,
    CJGUI_NATIVE_BRIDGE_COMMAND_BUFFER_STALE_QUEUE_TOKEN = -192,
    CJGUI_NATIVE_BRIDGE_COMMAND_BUFFER_QUEUE_TOKEN_NOT_BOUND = -193
} CjguiNativeBridgeCommandBufferLifecycleClassification;

typedef enum CjguiNativeBridgeRenderPassDescriptorLifecycleClassification {
    CJGUI_NATIVE_BRIDGE_RENDER_PASS_DESCRIPTOR_TOKEN_BOUND = 200,
    CJGUI_NATIVE_BRIDGE_RENDER_PASS_DESCRIPTOR_CREATE_MAIN_THREAD_REQUIRED =
        -200,
    CJGUI_NATIVE_BRIDGE_RENDER_PASS_DESCRIPTOR_DESTROY_MAIN_THREAD_REQUIRED =
        -201,
    CJGUI_NATIVE_BRIDGE_RENDER_PASS_DESCRIPTOR_INVALID_TOKEN_DENIED = -202,
    CJGUI_NATIVE_BRIDGE_RENDER_PASS_DESCRIPTOR_STALE_TOKEN_DENIED = -203,
    CJGUI_NATIVE_BRIDGE_RENDER_PASS_DESCRIPTOR_TOKEN_NOT_BOUND = -204,
    CJGUI_NATIVE_BRIDGE_RENDER_PASS_DESCRIPTOR_CAPACITY_EXHAUSTED = -205,
    CJGUI_NATIVE_BRIDGE_RENDER_PASS_DESCRIPTOR_DOUBLE_DESTROY_DENIED = -206,
    CJGUI_NATIVE_BRIDGE_RENDER_PASS_DESCRIPTOR_CREATION_FAILED = -207,
    CJGUI_NATIVE_BRIDGE_RENDER_PASS_DESCRIPTOR_OUT_TOKEN_REQUIRED = -208,
    CJGUI_NATIVE_BRIDGE_RENDER_PASS_DESCRIPTOR_COLOR_ATTACHMENT_STILL_BLOCKED =
        -209,
    CJGUI_NATIVE_BRIDGE_RENDER_PASS_DESCRIPTOR_ENCODER_CREATION_STILL_BLOCKED =
        -210,
    CJGUI_NATIVE_BRIDGE_RENDER_PASS_DESCRIPTOR_DRAWABLE_TEXTURE_STILL_BLOCKED =
        -211
} CjguiNativeBridgeRenderPassDescriptorLifecycleClassification;

typedef enum CjguiNativeBridgePipelineDescriptorLifecycleClassification {
    CJGUI_NATIVE_BRIDGE_PIPELINE_DESCRIPTOR_TOKEN_BOUND = 220,
    CJGUI_NATIVE_BRIDGE_PIPELINE_DESCRIPTOR_CONFIGURED = 221,
    CJGUI_NATIVE_BRIDGE_PIPELINE_DESCRIPTOR_COLOR_PIXEL_FORMAT_CONFIGURED = 222,
    CJGUI_NATIVE_BRIDGE_PIPELINE_DESCRIPTOR_SAMPLE_COUNT_CONFIGURED = 223,
    CJGUI_NATIVE_BRIDGE_PIPELINE_DESCRIPTOR_CREATE_MAIN_THREAD_REQUIRED = -220,
    CJGUI_NATIVE_BRIDGE_PIPELINE_DESCRIPTOR_DESTROY_MAIN_THREAD_REQUIRED = -221,
    CJGUI_NATIVE_BRIDGE_PIPELINE_DESCRIPTOR_INVALID_TOKEN_DENIED = -222,
    CJGUI_NATIVE_BRIDGE_PIPELINE_DESCRIPTOR_STALE_TOKEN_DENIED = -223,
    CJGUI_NATIVE_BRIDGE_PIPELINE_DESCRIPTOR_TOKEN_NOT_BOUND = -224,
    CJGUI_NATIVE_BRIDGE_PIPELINE_DESCRIPTOR_CAPACITY_EXHAUSTED = -225,
    CJGUI_NATIVE_BRIDGE_PIPELINE_DESCRIPTOR_DOUBLE_DESTROY_DENIED = -226,
    CJGUI_NATIVE_BRIDGE_PIPELINE_DESCRIPTOR_CREATION_FAILED = -227,
    CJGUI_NATIVE_BRIDGE_PIPELINE_DESCRIPTOR_OUT_TOKEN_REQUIRED = -228,
    CJGUI_NATIVE_BRIDGE_PIPELINE_STATE_CREATION_STILL_BLOCKED = -229,
    CJGUI_NATIVE_BRIDGE_PIPELINE_DESCRIPTOR_SHADER_LIBRARY_STILL_BLOCKED =
        -230,
    CJGUI_NATIVE_BRIDGE_PIPELINE_DESCRIPTOR_VERTEX_FUNCTION_STILL_BLOCKED =
        -231,
    CJGUI_NATIVE_BRIDGE_PIPELINE_DESCRIPTOR_FRAGMENT_FUNCTION_STILL_BLOCKED =
        -232,
    CJGUI_NATIVE_BRIDGE_PIPELINE_DESCRIPTOR_BLENDING_STILL_BLOCKED = -233,
    CJGUI_NATIVE_BRIDGE_PIPELINE_DESCRIPTOR_ENCODER_BINDING_STILL_BLOCKED =
        -234,
    CJGUI_NATIVE_BRIDGE_PIPELINE_DESCRIPTOR_INVALID_SAMPLE_COUNT = -235,
    CJGUI_NATIVE_BRIDGE_PIPELINE_DESCRIPTOR_COLOR_PIXEL_FORMAT_NOT_CONFIGURED =
        -236,
    CJGUI_NATIVE_BRIDGE_PIPELINE_DESCRIPTOR_SAMPLE_COUNT_NOT_CONFIGURED =
        -237,
    CJGUI_NATIVE_BRIDGE_PIPELINE_DESCRIPTOR_CONFIGURE_MAIN_THREAD_REQUIRED =
        -238,
    CJGUI_NATIVE_BRIDGE_PIPELINE_DESCRIPTOR_PIPELINE_STATE_DESTROY_BEFORE_DESCRIPTOR_REQUIRED =
        -239
} CjguiNativeBridgePipelineDescriptorLifecycleClassification;

typedef enum CjguiNativeBridgeShaderLibraryLifecycleClassification {
    CJGUI_NATIVE_BRIDGE_SHADER_SOURCE_CONTRACT_AVAILABLE = 240,
    CJGUI_NATIVE_BRIDGE_SHADER_LIBRARY_TOKEN_BOUND = 241,
    CJGUI_NATIVE_BRIDGE_SHADER_FUNCTION_VERTEX_BOUND = 242,
    CJGUI_NATIVE_BRIDGE_SHADER_FUNCTION_FRAGMENT_BOUND = 243,
    CJGUI_NATIVE_BRIDGE_SHADER_SOURCE_VALIDATED = 244,
    CJGUI_NATIVE_BRIDGE_SHADER_LIBRARY_CREATE_MAIN_THREAD_REQUIRED = -240,
    CJGUI_NATIVE_BRIDGE_SHADER_LIBRARY_DESTROY_MAIN_THREAD_REQUIRED = -241,
    CJGUI_NATIVE_BRIDGE_SHADER_LIBRARY_INVALID_TOKEN_DENIED = -242,
    CJGUI_NATIVE_BRIDGE_SHADER_LIBRARY_STALE_TOKEN_DENIED = -243,
    CJGUI_NATIVE_BRIDGE_SHADER_LIBRARY_TOKEN_NOT_BOUND = -244,
    CJGUI_NATIVE_BRIDGE_SHADER_LIBRARY_CAPACITY_EXHAUSTED = -245,
    CJGUI_NATIVE_BRIDGE_SHADER_LIBRARY_DOUBLE_DESTROY_DENIED = -246,
    CJGUI_NATIVE_BRIDGE_SHADER_LIBRARY_CREATION_FAILED = -247,
    CJGUI_NATIVE_BRIDGE_SHADER_LIBRARY_OUT_TOKEN_REQUIRED = -248,
    CJGUI_NATIVE_BRIDGE_SHADER_LIBRARY_INVALID_DEVICE_TOKEN = -249,
    CJGUI_NATIVE_BRIDGE_SHADER_LIBRARY_STALE_DEVICE_TOKEN = -250,
    CJGUI_NATIVE_BRIDGE_SHADER_LIBRARY_DEVICE_TOKEN_NOT_BOUND = -251,
    CJGUI_NATIVE_BRIDGE_SHADER_PIPELINE_STATE_CREATION_STILL_BLOCKED = -252,
    CJGUI_NATIVE_BRIDGE_SHADER_ENCODER_BINDING_STILL_BLOCKED = -253,
    CJGUI_NATIVE_BRIDGE_SHADER_DRAW_STILL_BLOCKED = -254,
    CJGUI_NATIVE_BRIDGE_SHADER_FUNCTION_MISSING = -255,
    CJGUI_NATIVE_BRIDGE_SHADER_FUNCTION_TABLE_CAPACITY_EXHAUSTED = -256,
    CJGUI_NATIVE_BRIDGE_SHADER_FUNCTION_LOOKUP_MAIN_THREAD_REQUIRED = -257,
    CJGUI_NATIVE_BRIDGE_SHADER_FUNCTION_DESTROY_MAIN_THREAD_REQUIRED = -258,
    CJGUI_NATIVE_BRIDGE_SHADER_FUNCTION_INVALID_LIBRARY_TOKEN = -259,
    CJGUI_NATIVE_BRIDGE_SHADER_FUNCTION_STALE_LIBRARY_TOKEN = -260,
    CJGUI_NATIVE_BRIDGE_SHADER_FUNCTION_LIBRARY_TOKEN_NOT_BOUND = -261,
    CJGUI_NATIVE_BRIDGE_SHADER_FUNCTION_INVALID_TOKEN_DENIED = -262,
    CJGUI_NATIVE_BRIDGE_SHADER_FUNCTION_STALE_TOKEN_DENIED = -263,
    CJGUI_NATIVE_BRIDGE_SHADER_FUNCTION_TOKEN_NOT_BOUND = -264,
    CJGUI_NATIVE_BRIDGE_SHADER_FUNCTION_DOUBLE_DESTROY_DENIED = -265,
    CJGUI_NATIVE_BRIDGE_SHADER_FUNCTION_OUT_TOKEN_REQUIRED = -266,
    CJGUI_NATIVE_BRIDGE_SHADER_FUNCTION_DESTROY_BEFORE_LIBRARY_REQUIRED = -267,
    CJGUI_NATIVE_BRIDGE_SHADER_FUNCTION_PIPELINE_STATE_DESTROY_BEFORE_FUNCTION_REQUIRED =
        -268
} CjguiNativeBridgeShaderLibraryLifecycleClassification;

typedef enum CjguiNativeBridgePipelineStateLifecycleClassification {
    CJGUI_NATIVE_BRIDGE_PIPELINE_STATE_TOKEN_BOUND = 260,
    CJGUI_NATIVE_BRIDGE_PIPELINE_STATE_CREATE_MAIN_THREAD_REQUIRED = -280,
    CJGUI_NATIVE_BRIDGE_PIPELINE_STATE_DESTROY_MAIN_THREAD_REQUIRED = -281,
    CJGUI_NATIVE_BRIDGE_PIPELINE_STATE_INVALID_TOKEN_DENIED = -282,
    CJGUI_NATIVE_BRIDGE_PIPELINE_STATE_STALE_TOKEN_DENIED = -283,
    CJGUI_NATIVE_BRIDGE_PIPELINE_STATE_TOKEN_NOT_BOUND = -284,
    CJGUI_NATIVE_BRIDGE_PIPELINE_STATE_CAPACITY_EXHAUSTED = -285,
    CJGUI_NATIVE_BRIDGE_PIPELINE_STATE_DOUBLE_DESTROY_DENIED = -286,
    CJGUI_NATIVE_BRIDGE_PIPELINE_STATE_CREATION_FAILED = -287,
    CJGUI_NATIVE_BRIDGE_PIPELINE_STATE_OUT_TOKEN_REQUIRED = -288,
    CJGUI_NATIVE_BRIDGE_PIPELINE_STATE_INVALID_DEVICE_TOKEN = -289,
    CJGUI_NATIVE_BRIDGE_PIPELINE_STATE_STALE_DEVICE_TOKEN = -290,
    CJGUI_NATIVE_BRIDGE_PIPELINE_STATE_DEVICE_TOKEN_NOT_BOUND = -291,
    CJGUI_NATIVE_BRIDGE_PIPELINE_STATE_INVALID_DESCRIPTOR_TOKEN = -292,
    CJGUI_NATIVE_BRIDGE_PIPELINE_STATE_STALE_DESCRIPTOR_TOKEN = -293,
    CJGUI_NATIVE_BRIDGE_PIPELINE_STATE_DESCRIPTOR_TOKEN_NOT_BOUND = -294,
    CJGUI_NATIVE_BRIDGE_PIPELINE_STATE_DESCRIPTOR_NOT_CONFIGURED = -295,
    CJGUI_NATIVE_BRIDGE_PIPELINE_STATE_INVALID_VERTEX_FUNCTION_TOKEN = -296,
    CJGUI_NATIVE_BRIDGE_PIPELINE_STATE_STALE_VERTEX_FUNCTION_TOKEN = -297,
    CJGUI_NATIVE_BRIDGE_PIPELINE_STATE_VERTEX_FUNCTION_TOKEN_NOT_BOUND = -298,
    CJGUI_NATIVE_BRIDGE_PIPELINE_STATE_VERTEX_FUNCTION_KIND_REQUIRED = -299,
    CJGUI_NATIVE_BRIDGE_PIPELINE_STATE_INVALID_FRAGMENT_FUNCTION_TOKEN = -300,
    CJGUI_NATIVE_BRIDGE_PIPELINE_STATE_STALE_FRAGMENT_FUNCTION_TOKEN = -301,
    CJGUI_NATIVE_BRIDGE_PIPELINE_STATE_FRAGMENT_FUNCTION_TOKEN_NOT_BOUND = -302,
    CJGUI_NATIVE_BRIDGE_PIPELINE_STATE_FRAGMENT_FUNCTION_KIND_REQUIRED = -303,
    CJGUI_NATIVE_BRIDGE_PIPELINE_STATE_ENCODER_BINDING_STILL_BLOCKED = -304,
    CJGUI_NATIVE_BRIDGE_PIPELINE_STATE_DRAW_STILL_BLOCKED = -305
} CjguiNativeBridgePipelineStateLifecycleClassification;

typedef enum CjguiNativeBridgeVertexBufferLifecycleClassification {
    CJGUI_NATIVE_BRIDGE_VERTEX_BUFFER_TOKEN_BOUND = 300,
    CJGUI_NATIVE_BRIDGE_VERTEX_BUFFER_DATA_UPLOADED = 301,
    CJGUI_NATIVE_BRIDGE_VERTEX_BUFFER_LAYOUT_POSITION_COLOR = 302,
    CJGUI_NATIVE_BRIDGE_VERTEX_BUFFER_CREATE_MAIN_THREAD_REQUIRED = -320,
    CJGUI_NATIVE_BRIDGE_VERTEX_BUFFER_DESTROY_MAIN_THREAD_REQUIRED = -321,
    CJGUI_NATIVE_BRIDGE_VERTEX_BUFFER_UPLOAD_MAIN_THREAD_REQUIRED = -322,
    CJGUI_NATIVE_BRIDGE_VERTEX_BUFFER_INVALID_TOKEN_DENIED = -323,
    CJGUI_NATIVE_BRIDGE_VERTEX_BUFFER_STALE_TOKEN_DENIED = -324,
    CJGUI_NATIVE_BRIDGE_VERTEX_BUFFER_TOKEN_NOT_BOUND = -325,
    CJGUI_NATIVE_BRIDGE_VERTEX_BUFFER_CAPACITY_EXHAUSTED = -326,
    CJGUI_NATIVE_BRIDGE_VERTEX_BUFFER_DOUBLE_DESTROY_DENIED = -327,
    CJGUI_NATIVE_BRIDGE_VERTEX_BUFFER_CREATION_FAILED = -328,
    CJGUI_NATIVE_BRIDGE_VERTEX_BUFFER_OUT_TOKEN_REQUIRED = -329,
    CJGUI_NATIVE_BRIDGE_VERTEX_BUFFER_INVALID_DEVICE_TOKEN = -330,
    CJGUI_NATIVE_BRIDGE_VERTEX_BUFFER_STALE_DEVICE_TOKEN = -331,
    CJGUI_NATIVE_BRIDGE_VERTEX_BUFFER_DEVICE_TOKEN_NOT_BOUND = -332,
    CJGUI_NATIVE_BRIDGE_VERTEX_BUFFER_DATA_NOT_UPLOADED = -333,
    CJGUI_NATIVE_BRIDGE_VERTEX_BUFFER_DATA_UPLOAD_FAILED = -334,
    CJGUI_NATIVE_BRIDGE_VERTEX_BUFFER_ENCODER_BINDING_STILL_BLOCKED = -335,
    CJGUI_NATIVE_BRIDGE_VERTEX_BUFFER_DRAW_STILL_BLOCKED = -336
} CjguiNativeBridgeVertexBufferLifecycleClassification;

typedef enum CjguiNativeBridgeDrawCallNoSubmitClassification {
    CJGUI_NATIVE_BRIDGE_DRAW_CALL_INPUT_BUNDLE_FACTS_READY = 320,
    CJGUI_NATIVE_BRIDGE_DRAW_CALL_ENCODER_REQUIRED = -340,
    CJGUI_NATIVE_BRIDGE_DRAW_CALL_PIPELINE_BINDING_REQUIRED = -341,
    CJGUI_NATIVE_BRIDGE_DRAW_CALL_VERTEX_BINDING_REQUIRED = -342,
    CJGUI_NATIVE_BRIDGE_DRAW_CALL_STILL_BLOCKED = -343
} CjguiNativeBridgeDrawCallNoSubmitClassification;

typedef enum CjguiNativeBridgeNsWindowHarnessLifecycleClassification {
    CJGUI_NATIVE_BRIDGE_NSWINDOW_HARNESS_TOKEN_BOUND = 360,
    CJGUI_NATIVE_BRIDGE_NSWINDOW_HARNESS_CREATE_MAIN_THREAD_REQUIRED = -360,
    CJGUI_NATIVE_BRIDGE_NSWINDOW_HARNESS_DESTROY_MAIN_THREAD_REQUIRED = -361,
    CJGUI_NATIVE_BRIDGE_NSWINDOW_HARNESS_INVALID_TOKEN_DENIED = -362,
    CJGUI_NATIVE_BRIDGE_NSWINDOW_HARNESS_STALE_TOKEN_DENIED = -363,
    CJGUI_NATIVE_BRIDGE_NSWINDOW_HARNESS_TOKEN_NOT_BOUND = -364,
    CJGUI_NATIVE_BRIDGE_NSWINDOW_HARNESS_CAPACITY_EXHAUSTED = -365,
    CJGUI_NATIVE_BRIDGE_NSWINDOW_HARNESS_DOUBLE_DESTROY_DENIED = -366,
    CJGUI_NATIVE_BRIDGE_NSWINDOW_HARNESS_CREATION_FAILED = -367,
    CJGUI_NATIVE_BRIDGE_NSWINDOW_HARNESS_OUT_TOKEN_REQUIRED = -368,
    CJGUI_NATIVE_BRIDGE_NSWINDOW_HARNESS_NEXT_DRAWABLE_STILL_BLOCKED = -369,
    CJGUI_NATIVE_BRIDGE_NSWINDOW_HARNESS_COMMAND_BUFFER_STILL_BLOCKED = -370,
    CJGUI_NATIVE_BRIDGE_NSWINDOW_HARNESS_RENDER_ENCODER_STILL_BLOCKED = -371,
    CJGUI_NATIVE_BRIDGE_NSWINDOW_HARNESS_PRESENT_STILL_BLOCKED = -372,
    CJGUI_NATIVE_BRIDGE_NSWINDOW_HARNESS_CONTENT_VIEW_ATTACHED = 380,
    CJGUI_NATIVE_BRIDGE_NSWINDOW_HARNESS_CONTENT_VIEW_NOT_ATTACHED = -380,
    CJGUI_NATIVE_BRIDGE_NSWINDOW_HARNESS_CONTENT_VIEW_ATTACH_MAIN_THREAD_REQUIRED =
        -381,
    CJGUI_NATIVE_BRIDGE_NSWINDOW_HARNESS_CONTENT_VIEW_INVALID_WINDOW_TOKEN =
        -382,
    CJGUI_NATIVE_BRIDGE_NSWINDOW_HARNESS_CONTENT_VIEW_STALE_WINDOW_TOKEN =
        -383,
    CJGUI_NATIVE_BRIDGE_NSWINDOW_HARNESS_CONTENT_VIEW_WINDOW_TOKEN_NOT_BOUND =
        -384,
    CJGUI_NATIVE_BRIDGE_NSWINDOW_HARNESS_CONTENT_VIEW_INVALID_VIEW_TOKEN =
        -385,
    CJGUI_NATIVE_BRIDGE_NSWINDOW_HARNESS_CONTENT_VIEW_STALE_VIEW_TOKEN = -386,
    CJGUI_NATIVE_BRIDGE_NSWINDOW_HARNESS_CONTENT_VIEW_VIEW_TOKEN_NOT_BOUND =
        -387,
    CJGUI_NATIVE_BRIDGE_NSWINDOW_HARNESS_CONTENT_VIEW_DOUBLE_ATTACH_DENIED =
        -388,
    CJGUI_NATIVE_BRIDGE_NSWINDOW_HARNESS_CONTENT_VIEW_DOUBLE_DETACH_DENIED =
        -389,
    CJGUI_NATIVE_BRIDGE_NSWINDOW_HARNESS_CONTENT_VIEW_DETACH_BEFORE_WINDOW_DESTROY_REQUIRED =
        -390,
    CJGUI_NATIVE_BRIDGE_NSWINDOW_HARNESS_CONTENT_VIEW_DETACH_BEFORE_VIEW_DESTROY_REQUIRED =
        -391,
    CJGUI_NATIVE_BRIDGE_NSWINDOW_HARNESS_CONTENT_VIEW_VISIBLE_ORDER_STILL_BLOCKED =
        -392,
    CJGUI_NATIVE_BRIDGE_NSWINDOW_VISIBLE_ORDER_APPLICATION_OWNERSHIP_REQUIRED =
        400,
    CJGUI_NATIVE_BRIDGE_NSWINDOW_VISIBLE_ORDER_BOUNDED_RUN_LOOP_REQUIRED = 401,
    CJGUI_NATIVE_BRIDGE_NSWINDOW_VISIBLE_ORDER_AUTO_CLOSE_REQUIRED = 402,
    CJGUI_NATIVE_BRIDGE_NSWINDOW_VISIBLE_ORDER_HEADLESS_FAIL_CLOSED = -400,
    CJGUI_NATIVE_BRIDGE_NSWINDOW_VISIBLE_ORDER_APPLICATION_CREATION_DEFERRED =
        -401,
    CJGUI_NATIVE_BRIDGE_NSWINDOW_VISIBLE_ORDER_ACTIVATION_DEFERRED = -402,
    CJGUI_NATIVE_BRIDGE_NSWINDOW_VISIBLE_ORDER_CONTENT_VIEW_REQUIRED = -403,
    CJGUI_NATIVE_BRIDGE_NSWINDOW_VISIBLE_ORDER_STILL_BLOCKED = -404,
    CJGUI_NATIVE_BRIDGE_NSWINDOW_VISIBLE_ORDER_DRAWABLE_STILL_BLOCKED = -405,
    CJGUI_NATIVE_BRIDGE_NSWINDOW_VISIBLE_ORDER_RENDER_STILL_BLOCKED = -406,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_GUARD_OWNERSHIP_REQUIRED = 420,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_GUARD_MAIN_THREAD_REQUIRED = 421,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_GUARD_BOUNDED_RUN_LOOP_REQUIRED = 422,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_GUARD_AUTO_CLOSE_REQUIRED = 423,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_GUARD_HEADLESS_FAIL_CLOSED = -420,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_GUARD_CREATION_DEFERRED = -421,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_GUARD_ACTIVATION_DEFERRED = -422,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_GUARD_ACTIVATION_POLICY_DEFERRED = -423,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_GUARD_EVENT_LOOP_DEFERRED = -424,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_GUARD_VISIBLE_ORDER_STILL_BLOCKED = -425,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_GUARD_DRAWABLE_STILL_BLOCKED = -426,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_GUARD_RENDER_STILL_BLOCKED = -427,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_SHARED_APPLICATION_GUARD_MAIN_THREAD_REQUIRED =
        430,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_SHARED_APPLICATION_GUARD_BOUNDED_RUN_LOOP_REQUIRED =
        431,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_SHARED_APPLICATION_GUARD_AUTO_CLOSE_REQUIRED =
        432,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_SHARED_APPLICATION_GUARD_TEARDOWN_BEFORE_VISIBLE_REQUIRED =
        433,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_SHARED_APPLICATION_GUARD_NON_USER_VISIBLE_REQUIRED =
        434,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_SHARED_APPLICATION_GUARD_ACCESSOR_BLOCKED =
        -430,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_SHARED_APPLICATION_GUARD_SINGLETON_CREATION_BLOCKED =
        -431,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_SHARED_APPLICATION_GUARD_HEADLESS_FAIL_CLOSED =
        -432,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_SHARED_APPLICATION_GUARD_ACTIVATION_POLICY_BLOCKED =
        -433,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_SHARED_APPLICATION_GUARD_ACTIVATION_BLOCKED =
        -434,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_SHARED_APPLICATION_GUARD_EVENT_LOOP_BLOCKED =
        -435,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_SHARED_APPLICATION_GUARD_VISIBLE_ORDER_STILL_BLOCKED =
        -436,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_SHARED_APPLICATION_GUARD_DRAWABLE_STILL_BLOCKED =
        -437,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_SHARED_APPLICATION_GUARD_RENDER_STILL_BLOCKED =
        -438,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_SHARED_APPLICATION_ACCESSOR_CALL_CONTAINMENT_NO_SINGLETON_ACCESSOR_CALL =
        440,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_SHARED_APPLICATION_ACCESSOR_CALL_CONTAINMENT_MAIN_THREAD_REQUIRED =
        441,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_SHARED_APPLICATION_ACCESSOR_CALL_CONTAINMENT_BOUNDED_RUN_LOOP_REQUIRED =
        442,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_SHARED_APPLICATION_ACCESSOR_CALL_CONTAINMENT_AUTO_CLOSE_REQUIRED =
        443,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_SHARED_APPLICATION_ACCESSOR_CALL_CONTAINMENT_TEARDOWN_BEFORE_VISIBLE_REQUIRED =
        444,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_SHARED_APPLICATION_ACCESSOR_CALL_CONTAINMENT_NON_USER_VISIBLE_REQUIRED =
        445,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_SHARED_APPLICATION_ACCESSOR_CALL_CONTAINMENT_ACCESSOR_BLOCKED =
        -440,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_SHARED_APPLICATION_ACCESSOR_CALL_CONTAINMENT_SINGLETON_CREATION_BLOCKED =
        -441,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_SHARED_APPLICATION_ACCESSOR_CALL_CONTAINMENT_APPLICATION_SIDE_EFFECT_BLOCKED =
        -442,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_SHARED_APPLICATION_ACCESSOR_CALL_CONTAINMENT_ACTIVATION_POLICY_BLOCKED =
        -443,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_SHARED_APPLICATION_ACCESSOR_CALL_CONTAINMENT_ACTIVATION_BLOCKED =
        -444,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_SHARED_APPLICATION_ACCESSOR_CALL_CONTAINMENT_EVENT_LOOP_BLOCKED =
        -445,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_SHARED_APPLICATION_ACCESSOR_CALL_CONTAINMENT_VISIBLE_ORDER_BLOCKED =
        -446,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_SHARED_APPLICATION_ACCESSOR_CALL_CONTAINMENT_DRAWABLE_BLOCKED =
        -447,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_SHARED_APPLICATION_ACCESSOR_CALL_CONTAINMENT_RENDER_BLOCKED =
        -448,
    CJGUI_NATIVE_BRIDGE_NSAPPLICATION_SHARED_APPLICATION_ACCESSOR_CALL_CONTAINMENT_BACKEND_READY_TRUTH_BLOCKED =
        -449
} CjguiNativeBridgeNsWindowHarnessLifecycleClassification;

/*
 * callable 只返回 dehydrated integer facts，或通过 out-token 返回 opaque token。
 * 它们不返回 pointer，不扩 public runtime API，也不表示 backend ready。
 */
uint32_t cjgui_native_bridge_surface_version(void);
uint32_t cjgui_native_bridge_surface_capabilities(void);
uint32_t cjgui_native_bridge_status_ok(void);
uint32_t cjgui_native_bridge_no_resource_admission(void);
int32_t cjgui_native_bridge_is_main_thread(void);
/*
 * macOS 系统“减少动态效果”偏好（accessibilityDisplayShouldReduceMotion）。
 * 只返回 0/1 的 dehydrated fact，不返回 pointer、不扩 public runtime API，
 * 也不表示 backend ready。非 Apple 平台或实现不可用时返回确定的 0。
 */
int32_t cjgui_macos_reduce_motion_enabled(void);
/*
 * macOS 系统外观（浅色/深色）与窗口可见/最小化的 dehydrated facts，供平台
 * 状态快照使用。只返回 0/1，不返回 pointer、不创建或改变任何对象，也不扩
 * public runtime API。
 * - cjgui_macos_effective_dark_mode：1 = 当前有效外观为深色，0 = 浅色或不可用。
 * - cjgui_macos_window_visible / _minimized：按 AppKit window number 查询已存在
 *   窗口；window_number <= 0、窗口不存在、NSApp 尚未创建或非 Apple 平台都返回
 *   确定的默认值 0。调用方不得用 0 断言“窗口不存在”，只应把它当作不可用。
 */
int32_t cjgui_macos_effective_dark_mode(void);
/*
 * Read NSColor.controlAccentColor after explicit conversion to sRGB. The
 * return value is -1 when unavailable; otherwise bit 24 is the success flag
 * and the low 24 bits are RRGGBB. Quantization bounds platform change
 * detection without exposing an AppKit object or an unspecified color space.
 */
int64_t cjgui_macos_control_accent_srgb8(void);
/// The normal AppKit launcher enables coalesced main-queue system-color reads.
/// No native object or application callback crosses this ABI.
void cjgui_macos_enable_accent_sampling(void);
int32_t cjgui_macos_window_visible(int64_t window_number);
int32_t cjgui_macos_window_minimized(int64_t window_number);
uint64_t cjgui_native_bridge_token_invalid(void);
uint32_t cjgui_native_bridge_token_table_capacity(void);
uint32_t cjgui_native_bridge_token_table_enabled(void);
int32_t cjgui_native_bridge_token_classify(uint64_t token);
uint64_t cjgui_native_bridge_token_issue(void);
int32_t cjgui_native_bridge_token_revoke(uint64_t token);
int32_t cjgui_native_bridge_teardown_admission(uint64_t token);
int32_t cjgui_native_bridge_destroy_not_supported(void);
int32_t cjgui_native_bridge_revoke_before_destroy_required(void);
int32_t cjgui_native_bridge_double_destroy_classify(uint64_t token);
int32_t cjgui_native_bridge_appkit_import_available(void);
int32_t cjgui_native_bridge_appkit_no_object_admission(void);
int32_t cjgui_native_bridge_platform_object_create_still_blocked(void);
int32_t cjgui_native_bridge_appkit_nswindow_class_available(void);
int32_t cjgui_native_bridge_appkit_nsview_class_available(void);
int32_t cjgui_native_bridge_appkit_class_lookup_no_object_admission(void);
int32_t cjgui_native_bridge_platform_object_allocation_still_blocked(void);
int32_t cjgui_native_bridge_appkit_platform_object_main_thread_required(void);
int32_t cjgui_native_bridge_appkit_platform_object_main_thread_admitted(void);
int32_t cjgui_native_bridge_appkit_platform_object_background_thread_denied(void);
int32_t cjgui_native_bridge_appkit_platform_object_creation_still_blocked(void);
int32_t cjgui_native_bridge_platform_object_create_no_object_admission(void);
int32_t cjgui_native_bridge_platform_object_create_requires_main_thread(void);
int32_t cjgui_native_bridge_platform_object_create_requires_token_contract(void);
int32_t cjgui_native_bridge_platform_object_create_allocation_blocked(void);
uint32_t cjgui_native_bridge_nsview_table_capacity(void);
uint32_t cjgui_native_bridge_nsview_table_enabled(void);
int32_t cjgui_native_bridge_nsview_table_empty(void);
int32_t cjgui_native_bridge_nsview_table_token_classify(uint64_t token);
int32_t cjgui_native_bridge_nsview_table_allocation_still_blocked(void);
int32_t cjgui_native_bridge_nsview_table_destroy_still_blocked(void);
int32_t cjgui_native_bridge_nsview_create(uint64_t* out_token);
int32_t cjgui_native_bridge_nsview_destroy(uint64_t token);
int32_t cjgui_native_bridge_nsview_token_classify(uint64_t token);
uint32_t cjgui_native_bridge_nsview_table_occupied_count(void);
int32_t cjgui_native_bridge_nsview_double_destroy_classify(uint64_t token);
int32_t cjgui_native_bridge_nsview_destroy_requires_main_thread(void);
int32_t cjgui_native_bridge_quartzcore_import_available(void);
int32_t cjgui_native_bridge_cametallayer_class_available(void);
int32_t cjgui_native_bridge_cametallayer_no_attach_admission(void);
int32_t cjgui_native_bridge_cametallayer_allocation_still_blocked(void);
int32_t cjgui_native_bridge_cametallayer_device_binding_still_blocked(void);
int32_t cjgui_native_bridge_cametallayer_allocation_feasible(void);
int32_t cjgui_native_bridge_cametallayer_allocation_requires_main_thread(void);
int32_t cjgui_native_bridge_cametallayer_allocation_no_attach_admission(void);
int32_t cjgui_native_bridge_cametallayer_allocation_device_binding_blocked(void);
int32_t cjgui_native_bridge_cametallayer_allocation_feasibility_probe(void);
uint32_t cjgui_native_bridge_cametallayer_table_capacity(void);
uint32_t cjgui_native_bridge_cametallayer_table_enabled(void);
int32_t cjgui_native_bridge_cametallayer_table_empty(void);
int32_t cjgui_native_bridge_cametallayer_table_token_classify(uint64_t token);
int32_t cjgui_native_bridge_cametallayer_table_allocation_still_blocked(void);
int32_t cjgui_native_bridge_cametallayer_table_destroy_still_blocked(void);
int32_t cjgui_native_bridge_cametallayer_create(uint64_t* out_token);
int32_t cjgui_native_bridge_cametallayer_destroy(uint64_t token);
int32_t cjgui_native_bridge_cametallayer_token_classify(uint64_t token);
uint32_t cjgui_native_bridge_cametallayer_table_occupied_count(void);
int32_t cjgui_native_bridge_cametallayer_double_destroy_classify(uint64_t token);
int32_t cjgui_native_bridge_cametallayer_destroy_requires_main_thread(void);
int32_t cjgui_native_bridge_cametallayer_attach_to_nsview(
    uint64_t layer_token,
    uint64_t view_token
);
int32_t cjgui_native_bridge_cametallayer_detach_from_nsview(
    uint64_t layer_token,
    uint64_t view_token
);
int32_t cjgui_native_bridge_cametallayer_attachment_classify(
    uint64_t layer_token,
    uint64_t view_token
);
int32_t cjgui_native_bridge_cametallayer_double_detach_classify(
    uint64_t layer_token,
    uint64_t view_token
);
int32_t cjgui_native_bridge_cametallayer_attach_requires_main_thread(void);
int32_t
cjgui_native_bridge_cametallayer_device_binding_after_attach_still_blocked(void);
int32_t cjgui_native_bridge_metal_import_available(void);
int32_t cjgui_native_bridge_metal_default_device_available(void);
int32_t cjgui_native_bridge_metal_device_no_command_queue_admission(void);
int32_t cjgui_native_bridge_metal_device_creation_still_blocked(void);
uint32_t cjgui_native_bridge_metal_device_table_capacity(void);
uint32_t cjgui_native_bridge_metal_device_table_enabled(void);
uint32_t cjgui_native_bridge_metal_device_table_occupied_count(void);
int32_t cjgui_native_bridge_metal_default_device_create(uint64_t* out_token);
int32_t cjgui_native_bridge_metal_device_destroy(uint64_t token);
int32_t cjgui_native_bridge_metal_device_token_classify(uint64_t token);
int32_t cjgui_native_bridge_metal_device_double_destroy_classify(uint64_t token);
int32_t cjgui_native_bridge_metal_device_create_requires_main_thread(void);
int32_t cjgui_native_bridge_metal_device_destroy_requires_main_thread(void);
int32_t cjgui_native_bridge_metal_device_command_queue_still_blocked(void);
int32_t cjgui_native_bridge_cametallayer_bind_metal_device(
    uint64_t layer_token,
    uint64_t device_token
);
int32_t cjgui_native_bridge_cametallayer_unbind_metal_device(
    uint64_t layer_token,
    uint64_t device_token
);
int32_t cjgui_native_bridge_cametallayer_device_binding_classify(
    uint64_t layer_token,
    uint64_t device_token
);
int32_t cjgui_native_bridge_cametallayer_double_unbind_device_classify(
    uint64_t layer_token,
    uint64_t device_token
);
int32_t cjgui_native_bridge_cametallayer_device_binding_requires_main_thread(void);
int32_t cjgui_native_bridge_cametallayer_drawable_acquisition_still_blocked(void);
uint32_t cjgui_native_bridge_command_queue_table_capacity(void);
uint32_t cjgui_native_bridge_command_queue_table_enabled(void);
uint32_t cjgui_native_bridge_command_queue_table_occupied_count(void);
int32_t cjgui_native_bridge_command_queue_create(
    uint64_t device_token,
    uint64_t* out_queue_token
);
int32_t cjgui_native_bridge_command_queue_destroy(uint64_t queue_token);
int32_t cjgui_native_bridge_command_queue_token_classify(uint64_t queue_token);
int32_t
cjgui_native_bridge_command_queue_double_destroy_classify(uint64_t queue_token);
int32_t cjgui_native_bridge_command_queue_create_requires_main_thread(void);
int32_t cjgui_native_bridge_command_queue_destroy_requires_main_thread(void);
int32_t cjgui_native_bridge_command_buffer_creation_still_blocked(void);
uint32_t cjgui_native_bridge_command_buffer_table_capacity(void);
uint32_t cjgui_native_bridge_command_buffer_table_enabled(void);
uint32_t cjgui_native_bridge_command_buffer_table_occupied_count(void);
int32_t cjgui_native_bridge_command_buffer_create(
    uint64_t queue_token,
    uint64_t* out_buffer_token
);
int32_t cjgui_native_bridge_command_buffer_destroy(uint64_t buffer_token);
int32_t cjgui_native_bridge_command_buffer_token_classify(
    uint64_t buffer_token
);
int32_t
cjgui_native_bridge_command_buffer_double_destroy_classify(uint64_t buffer_token);
int32_t cjgui_native_bridge_command_buffer_create_requires_main_thread(void);
int32_t cjgui_native_bridge_command_buffer_destroy_requires_main_thread(void);
int32_t cjgui_native_bridge_command_buffer_commit_still_blocked(void);
int32_t cjgui_native_bridge_command_buffer_encoder_creation_still_blocked(void);
uint32_t cjgui_native_bridge_render_pass_descriptor_table_capacity(void);
uint32_t cjgui_native_bridge_render_pass_descriptor_table_enabled(void);
uint32_t cjgui_native_bridge_render_pass_descriptor_table_occupied_count(void);
int32_t cjgui_native_bridge_render_pass_descriptor_create(
    uint64_t* out_descriptor_token
);
int32_t cjgui_native_bridge_render_pass_descriptor_destroy(
    uint64_t descriptor_token
);
int32_t cjgui_native_bridge_render_pass_descriptor_token_classify(
    uint64_t descriptor_token
);
int32_t cjgui_native_bridge_render_pass_descriptor_double_destroy_classify(
    uint64_t descriptor_token
);
int32_t cjgui_native_bridge_render_pass_descriptor_create_requires_main_thread(
    void
);
int32_t cjgui_native_bridge_render_pass_descriptor_destroy_requires_main_thread(
    void
);
int32_t cjgui_native_bridge_render_pass_descriptor_color_attachment_still_blocked(
    void
);
int32_t cjgui_native_bridge_render_pass_descriptor_encoder_creation_still_blocked(
    void
);
int32_t cjgui_native_bridge_render_pass_descriptor_drawable_texture_still_blocked(
    void
);
uint32_t cjgui_native_bridge_pipeline_descriptor_table_capacity(void);
uint32_t cjgui_native_bridge_pipeline_descriptor_table_enabled(void);
uint32_t cjgui_native_bridge_pipeline_descriptor_table_occupied_count(void);
int32_t cjgui_native_bridge_pipeline_descriptor_create(
    uint64_t* out_descriptor_token
);
int32_t cjgui_native_bridge_pipeline_descriptor_destroy(
    uint64_t descriptor_token
);
int32_t cjgui_native_bridge_pipeline_descriptor_token_classify(
    uint64_t descriptor_token
);
int32_t cjgui_native_bridge_pipeline_descriptor_double_destroy_classify(
    uint64_t descriptor_token
);
int32_t cjgui_native_bridge_pipeline_descriptor_create_requires_main_thread(
    void
);
int32_t cjgui_native_bridge_pipeline_descriptor_destroy_requires_main_thread(
    void
);
int32_t cjgui_native_bridge_pipeline_descriptor_configure_requires_main_thread(
    void
);
int32_t cjgui_native_bridge_pipeline_descriptor_configure_no_draw(
    uint64_t descriptor_token
);
int32_t cjgui_native_bridge_pipeline_descriptor_color_pixel_format_classify(
    uint64_t descriptor_token
);
int32_t cjgui_native_bridge_pipeline_descriptor_sample_count_classify(
    uint64_t descriptor_token
);
int32_t cjgui_native_bridge_pipeline_descriptor_shader_library_still_blocked(
    void
);
int32_t cjgui_native_bridge_pipeline_descriptor_vertex_function_still_blocked(
    void
);
int32_t cjgui_native_bridge_pipeline_descriptor_fragment_function_still_blocked(
    void
);
int32_t cjgui_native_bridge_pipeline_descriptor_blending_still_blocked(void);
int32_t cjgui_native_bridge_pipeline_descriptor_encoder_binding_still_blocked(
    void
);
int32_t cjgui_native_bridge_pipeline_state_creation_still_blocked(void);
int32_t cjgui_native_bridge_shader_source_contract_available(void);
uint32_t cjgui_native_bridge_shader_library_table_capacity(void);
uint32_t cjgui_native_bridge_shader_library_table_enabled(void);
uint32_t cjgui_native_bridge_shader_library_table_occupied_count(void);
int32_t cjgui_native_bridge_shader_library_create(
    uint64_t device_token,
    uint64_t* out_library_token
);
int32_t cjgui_native_bridge_shader_library_destroy(uint64_t library_token);
int32_t cjgui_native_bridge_shader_library_token_classify(
    uint64_t library_token
);
int32_t cjgui_native_bridge_shader_library_double_destroy_classify(
    uint64_t library_token
);
int32_t cjgui_native_bridge_shader_library_create_requires_main_thread(void);
int32_t cjgui_native_bridge_shader_library_destroy_requires_main_thread(void);
uint32_t cjgui_native_bridge_shader_function_table_capacity(void);
uint32_t cjgui_native_bridge_shader_function_table_enabled(void);
uint32_t cjgui_native_bridge_shader_function_table_occupied_count(void);
int32_t cjgui_native_bridge_shader_function_lookup_vertex(
    uint64_t library_token,
    uint64_t* out_function_token
);
int32_t cjgui_native_bridge_shader_function_lookup_fragment(
    uint64_t library_token,
    uint64_t* out_function_token
);
int32_t cjgui_native_bridge_shader_function_destroy(uint64_t function_token);
int32_t cjgui_native_bridge_shader_function_token_classify(
    uint64_t function_token
);
int32_t cjgui_native_bridge_shader_function_double_destroy_classify(
    uint64_t function_token
);
int32_t cjgui_native_bridge_shader_function_lookup_requires_main_thread(void);
int32_t cjgui_native_bridge_shader_function_destroy_requires_main_thread(void);
int32_t cjgui_native_bridge_shader_function_missing_classify(void);
int32_t cjgui_native_bridge_shader_pipeline_state_creation_still_blocked(void);
int32_t cjgui_native_bridge_shader_encoder_binding_still_blocked(void);
int32_t cjgui_native_bridge_shader_draw_still_blocked(void);
uint32_t cjgui_native_bridge_pipeline_state_table_capacity(void);
uint32_t cjgui_native_bridge_pipeline_state_table_enabled(void);
uint32_t cjgui_native_bridge_pipeline_state_table_occupied_count(void);
int32_t cjgui_native_bridge_pipeline_state_create(
    uint64_t device_token,
    uint64_t descriptor_token,
    uint64_t vertex_function_token,
    uint64_t fragment_function_token,
    uint64_t* out_pipeline_state_token
);
int32_t cjgui_native_bridge_pipeline_state_destroy(
    uint64_t pipeline_state_token
);
int32_t cjgui_native_bridge_pipeline_state_token_classify(
    uint64_t pipeline_state_token
);
int32_t cjgui_native_bridge_pipeline_state_double_destroy_classify(
    uint64_t pipeline_state_token
);
int32_t cjgui_native_bridge_pipeline_state_create_requires_main_thread(void);
int32_t cjgui_native_bridge_pipeline_state_destroy_requires_main_thread(void);
int32_t cjgui_native_bridge_pipeline_state_encoder_binding_still_blocked(void);
int32_t cjgui_native_bridge_pipeline_state_draw_still_blocked(void);
uint32_t cjgui_native_bridge_vertex_buffer_table_capacity(void);
uint32_t cjgui_native_bridge_vertex_buffer_table_enabled(void);
uint32_t cjgui_native_bridge_vertex_buffer_table_occupied_count(void);
int32_t cjgui_native_bridge_vertex_buffer_create(
    uint64_t device_token,
    uint64_t* out_buffer_token
);
int32_t cjgui_native_bridge_vertex_buffer_destroy(uint64_t buffer_token);
int32_t cjgui_native_bridge_vertex_buffer_token_classify(
    uint64_t buffer_token
);
int32_t cjgui_native_bridge_vertex_buffer_double_destroy_classify(
    uint64_t buffer_token
);
int32_t cjgui_native_bridge_vertex_buffer_upload_static_triangle(
    uint64_t buffer_token
);
int32_t cjgui_native_bridge_vertex_buffer_data_classify(
    uint64_t buffer_token
);
int32_t cjgui_native_bridge_vertex_buffer_create_requires_main_thread(void);
int32_t cjgui_native_bridge_vertex_buffer_destroy_requires_main_thread(void);
int32_t cjgui_native_bridge_vertex_buffer_upload_requires_main_thread(void);
int32_t cjgui_native_bridge_vertex_buffer_layout_position_color(void);
int32_t cjgui_native_bridge_vertex_buffer_encoder_binding_still_blocked(void);
int32_t cjgui_native_bridge_vertex_buffer_draw_still_blocked(void);
int32_t cjgui_native_bridge_draw_call_encoder_required(void);
int32_t cjgui_native_bridge_draw_call_pipeline_binding_required(void);
int32_t cjgui_native_bridge_draw_call_vertex_binding_required(void);
int32_t cjgui_native_bridge_draw_call_still_blocked(void);
uint32_t cjgui_native_bridge_nswindow_harness_table_capacity(void);
uint32_t cjgui_native_bridge_nswindow_harness_table_enabled(void);
uint32_t cjgui_native_bridge_nswindow_harness_table_occupied_count(void);
int32_t cjgui_native_bridge_nswindow_harness_create(uint64_t* out_window_token);
int32_t cjgui_native_bridge_nswindow_harness_destroy(uint64_t window_token);
int32_t
cjgui_native_bridge_nswindow_harness_token_classify(uint64_t window_token);
int32_t
cjgui_native_bridge_nswindow_harness_double_destroy_classify(
    uint64_t window_token
);
int32_t cjgui_native_bridge_nswindow_harness_create_requires_main_thread(void);
int32_t cjgui_native_bridge_nswindow_harness_destroy_requires_main_thread(void);
int32_t cjgui_native_bridge_nswindow_harness_next_drawable_still_blocked(void);
int32_t cjgui_native_bridge_nswindow_harness_command_buffer_still_blocked(void);
int32_t cjgui_native_bridge_nswindow_harness_render_encoder_still_blocked(void);
int32_t cjgui_native_bridge_nswindow_harness_present_still_blocked(void);
int32_t cjgui_native_bridge_nswindow_harness_content_view_attach(
    uint64_t window_token,
    uint64_t view_token
);
int32_t cjgui_native_bridge_nswindow_harness_content_view_detach(
    uint64_t window_token,
    uint64_t view_token
);
int32_t
cjgui_native_bridge_nswindow_harness_content_view_attachment_classify(
    uint64_t window_token,
    uint64_t view_token
);
int32_t
cjgui_native_bridge_nswindow_harness_content_view_double_attach_classify(
    uint64_t window_token,
    uint64_t view_token
);
int32_t
cjgui_native_bridge_nswindow_harness_content_view_double_detach_classify(
    uint64_t window_token,
    uint64_t view_token
);
int32_t
cjgui_native_bridge_nswindow_harness_content_view_attach_requires_main_thread(
    void
);
int32_t
cjgui_native_bridge_nswindow_harness_content_view_visible_order_still_blocked(
    void
);
int32_t
cjgui_native_bridge_nswindow_visible_order_application_ownership_required(
    void
);
int32_t
cjgui_native_bridge_nswindow_visible_order_application_creation_deferred(
    void
);
int32_t cjgui_native_bridge_nswindow_visible_order_activation_deferred(void);
int32_t
cjgui_native_bridge_nswindow_visible_order_bounded_run_loop_required(void);
int32_t cjgui_native_bridge_nswindow_visible_order_auto_close_required(void);
int32_t cjgui_native_bridge_nswindow_visible_order_headless_fail_closed(void);
int32_t cjgui_native_bridge_nswindow_visible_order_content_view_required(void);
int32_t cjgui_native_bridge_nswindow_visible_order_still_blocked(void);
int32_t cjgui_native_bridge_nswindow_visible_order_drawable_still_blocked(void);
int32_t cjgui_native_bridge_nswindow_visible_order_render_still_blocked(void);
int32_t cjgui_native_bridge_nsapplication_guard_ownership_required(void);
int32_t cjgui_native_bridge_nsapplication_guard_main_thread_required(void);
int32_t cjgui_native_bridge_nsapplication_guard_creation_deferred(void);
int32_t cjgui_native_bridge_nsapplication_guard_activation_deferred(void);
int32_t cjgui_native_bridge_nsapplication_guard_activation_policy_deferred(void);
int32_t cjgui_native_bridge_nsapplication_guard_event_loop_deferred(void);
int32_t cjgui_native_bridge_nsapplication_guard_bounded_run_loop_required(void);
int32_t cjgui_native_bridge_nsapplication_guard_auto_close_required(void);
int32_t cjgui_native_bridge_nsapplication_guard_headless_fail_closed(void);
int32_t cjgui_native_bridge_nsapplication_guard_visible_order_still_blocked(void);
int32_t cjgui_native_bridge_nsapplication_guard_drawable_still_blocked(void);
int32_t cjgui_native_bridge_nsapplication_guard_render_still_blocked(void);
int32_t
cjgui_native_bridge_nsapplication_shared_application_guard_accessor_blocked(
    void
);
int32_t
cjgui_native_bridge_nsapplication_shared_application_guard_singleton_creation_blocked(
    void
);
int32_t
cjgui_native_bridge_nsapplication_shared_application_guard_main_thread_required(
    void
);
int32_t
cjgui_native_bridge_nsapplication_shared_application_guard_bounded_run_loop_required(
    void
);
int32_t
cjgui_native_bridge_nsapplication_shared_application_guard_auto_close_required(
    void
);
int32_t
cjgui_native_bridge_nsapplication_shared_application_guard_headless_fail_closed(
    void
);
int32_t
cjgui_native_bridge_nsapplication_shared_application_guard_teardown_before_visible_required(
    void
);
int32_t
cjgui_native_bridge_nsapplication_shared_application_guard_non_user_visible_required(
    void
);
int32_t
cjgui_native_bridge_nsapplication_shared_application_guard_activation_policy_blocked(
    void
);
int32_t
cjgui_native_bridge_nsapplication_shared_application_guard_activation_blocked(
    void
);
int32_t
cjgui_native_bridge_nsapplication_shared_application_guard_event_loop_blocked(
    void
);
int32_t
cjgui_native_bridge_nsapplication_shared_application_guard_visible_order_still_blocked(
    void
);
int32_t
cjgui_native_bridge_nsapplication_shared_application_guard_drawable_still_blocked(
    void
);
int32_t
cjgui_native_bridge_nsapplication_shared_application_guard_render_still_blocked(
    void
);
int32_t
cjgui_native_bridge_nsapplication_shared_application_accessor_call_containment_accessor_blocked(
    void
);
int32_t
cjgui_native_bridge_nsapplication_shared_application_accessor_call_containment_no_singleton_accessor_call(
    void
);
int32_t
cjgui_native_bridge_nsapplication_shared_application_accessor_call_containment_singleton_creation_blocked(
    void
);
int32_t
cjgui_native_bridge_nsapplication_shared_application_accessor_call_containment_main_thread_required(
    void
);
int32_t
cjgui_native_bridge_nsapplication_shared_application_accessor_call_containment_bounded_run_loop_required(
    void
);
int32_t
cjgui_native_bridge_nsapplication_shared_application_accessor_call_containment_auto_close_required(
    void
);
int32_t
cjgui_native_bridge_nsapplication_shared_application_accessor_call_containment_teardown_before_visible_required(
    void
);
int32_t
cjgui_native_bridge_nsapplication_shared_application_accessor_call_containment_non_user_visible_required(
    void
);
int32_t
cjgui_native_bridge_nsapplication_shared_application_accessor_call_containment_application_side_effect_blocked(
    void
);
int32_t
cjgui_native_bridge_nsapplication_shared_application_accessor_call_containment_activation_policy_blocked(
    void
);
int32_t
cjgui_native_bridge_nsapplication_shared_application_accessor_call_containment_activation_blocked(
    void
);
int32_t
cjgui_native_bridge_nsapplication_shared_application_accessor_call_containment_event_loop_blocked(
    void
);
int32_t
cjgui_native_bridge_nsapplication_shared_application_accessor_call_containment_visible_order_blocked(
    void
);
int32_t
cjgui_native_bridge_nsapplication_shared_application_accessor_call_containment_drawable_blocked(
    void
);
int32_t
cjgui_native_bridge_nsapplication_shared_application_accessor_call_containment_render_blocked(
    void
);
int32_t
cjgui_native_bridge_nsapplication_shared_application_accessor_call_containment_backend_ready_truth_blocked(
    void
);

#ifdef __cplusplus
}
#endif

#endif
